# Generated by Django 4.1.1 on 2022-11-17 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='date published')),
                ('pw', models.CharField(max_length=300)),
                ('worker_min', models.CharField(max_length=100)),
                ('worker_max', models.CharField(max_length=100)),
                ('pod_min', models.CharField(max_length=100)),
                ('pod_max', models.CharField(max_length=100)),
                ('lb_address', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': '',
            },
        ),
    ]
