# Generated by Django 4.1.3 on 2022-11-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
